blog.liiion911.ru/chive/protected/controllers/RowController.php
<?php

/*
 * Chive - web based MySQL database management
 * Copyright (C) 2010 Fusonic GmbH
 *
 * This file is part of Chive.
 *
 * Chive is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Chive is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */


class RowController extends Controller
{
	public $schema;
	public $table;
	public $view;
	
	/**
	 * @var Table
	 */
	public $_table;

	/**
	 * @var Default layout for this controller
	 */
	public $layout = 'schema';

	public function __construct($id, $module=null)
	{
		if(Yii::app()->request->isAjaxRequest)
			$this->layout = false;
			
		$request = Yii::app()->getRequest();
		
		$this->schema =	$request->getParam('schema');
		$this->table = $request->getParam('table');
		
		$this->_table = Table::model()->findByPk(array(
			'TABLE_SCHEMA' => $this->schema,
			'TABLE_NAME' => $this->table,
		));
		
		if($this->_table->TABLE_TYPE == 'VIEW')
		{
			$this->view = $this->table;
		}
		
		parent::__construct($id, $module);
		$this->connectDb($this->schema);
		
		// Set row values
		Row::$db = $this->db;
		Row::$schema = $this->schema;
		Row::$table = $this->table;
		
	}

	/**
	 * Insert a new row
	 * 
	 */
	public function actionInsert()
	{
		$response = new AjaxResponse();
		
		if($this->view)
		{
			$this->layout = '_view';
		}
		else
		{
			$this->layout = '_table';
		}

		$row = new Row();
		
		if(isset($_POST['Row']))
		{
			
			foreach($_POST['Row'] AS $attribute=>$value) 
			{
				// NULL value
				if(isset($_POST[$attribute]['null']))
				{
					$row->setAttribute($attribute, null);
				}
	
				// RAW
				// @todo (rponudic) implement multiple sets
				elseif('type' == 'multiple_set')
				{
					
				}
				
				// FILE
				elseif(isset($_FILES['Row']['tmp_name'][$attribute]) && is_file($_FILES['Row']['tmp_name'][$attribute]))
				{
					
					$file = '0x' . bin2hex(file_get_contents($_FILES['Row']['tmp_name'][$attribute]));
					$row->setHex($attribute);
					$row->setAttribute($attribute, $file);
					
				}
				
				// DEFAULT
				else
				{
					$row->setAttribute($attribute, $value);
				}
				
				// FUNCTIONS
				if(isset($_POST[$attribute]['function']) && $_POST[$attribute]['function'])
				{
					$row->setFunction($attribute, $_POST[$attribute]['function']);
				}
				
			}
			
			try 
			{
				$sql = $row->insert();
				
				// Try to find last inserted id if this table has an auto increment value
				if($this->_table->getHasAutoIncrementColumn())
				{
					$notification = Yii::t('core', 'successInsertRowWithIdX', array(
						"{id}" => $this->db->getLastInsertID(),
					));	
				}
				else
				{
					$notification = Yii::t('core', 'successInsertRow');
				}
				
				$response->addNotification('success', $notification, null, $sql);
				
				if($_POST['insertAndReturn'])
				{
					$response->refresh = true;
				}
				else
				{
					$response->redirectUrl = '#tables/' . $this->table . '/browse';
				}
				
			}
			catch (DbException $ex) 
			{
				$response->refresh = false;
				$response->addNotification('error', Yii::t('core', 'errorInsertRow'), $ex->getText(), $ex->getSql());
			}
			
			$this->sendJSON($response);
		
		}
		elseif(isset($_POST['attributes']))
		{
			$attributes = CJSON::decode($_POST['attributes'], true);
			$fromRow = Row::model()->findByAttributes($attributes);
			
			foreach($this->_table->columns as $column)
			{
				if($column->EXTRA != "auto_increment")
				{
					$row->{$column->COLUMN_NAME} = $fromRow->{$column->COLUMN_NAME};
				}
			}
		}
		
		$data = array(
			'row' => $row,
			'functions' => Row::$functions,
		);
		
		$data['formBody'] = $this->renderPartial('formBody', $data, true);
		
		$this->render('insert', $data);

	}
	
	public function actionUpdate()
	{

		$response = new AjaxResponse();

		// Take other solution::
		$newValue = Yii::app()->getRequest()->getParam('value');
		$column = Yii::app()->getRequest()->getParam('column');
		$isNull = Yii::app()->getRequest()->getParam('isNull');
		$attributes = CJSON::decode(Yii::app()->getRequest()->getParam('attributes'), true);
		
		$rows = Row::model()->findAllByAttributes($attributes);
		$row = $rows[0];
		
		// FILE (blob)
		if(isset($_FILES['value']))
		{
			$row->setHex($column);
			$newValue = '0x' . bin2hex(file_get_contents($_FILES['value']['tmp_name']));
			// Refresh if type s file 
			$response->refresh = true;
		}

		if($isNull)
		{
			$newValue = null;
		}
		
		try {

			$row->setAttribute($column, $newValue);
			$sql = $row->save();
			
			$showFullColumnContent = Yii::app()->user->settings->get('showFullColumnContent', 'schema.table.browse', $this->schema . '.' . $this->table);
			
			$visibleValue = CHtml::encode($row->getAttribute($column));
			
			if($isNull)
			{
				$visibleValue = '<span class="null">NULL</span>';
			}
			elseif(!$showFullColumnContent)
			{
				$visibleValue = StringUtil::cutText($visibleValue, 100);
			}

			$response->addData(null, array(
				'value' => ($isNull ? 'NULL' : $row->getAttribute($column)),
				'column' => $column,
				'identifier' => $row->getIdentifier(),
				'isNull' => $isNull,
				'visibleValue' => $visibleValue
			));
			
			$cmd = new CDbCommand($this->db, 'SHOW WARNINGS');
			$warnings = $cmd->queryAll(true);
			
			if(count($warnings) > 0)
			{
				$response->refresh = true;
				foreach($warnings AS $warning)
				{
					$response->addNotification('warning', $warning['Message'], null);
				}
			}
			
			$response->addNotification('success', Yii::t('core', 'successUpdateRow'), null, $sql);


		}
		catch (DbException $ex)
		{
			$response->addNotification('error', Yii::t('core', 'errorUpdateRow'), $ex->getText(), $ex->getSql());
			$response->addData(null, array('error'=>true));
		}

		$this->sendJSON($response);

	}

	public function actionDelete()
	{

		$response = new AjaxResponse();

		$data = CJSON::decode($_POST['data'], true);
		
		$sql = "";
		
		try
		{
			foreach($data AS $attributes)
			{
				$row = Row::model()->findByAttributes($attributes);
				$sql .= $row->delete() . "\n\n";
				
			}
		}
		catch (DbException $ex)
		{
			$response->addNotification('error', Yii::t('core', 'errorDeleteRow'), $ex->getText(), $sql, array('isSticky'=>true));
		}

		$response->refresh = true;
		$response->addNotification('success', Yii::t('core', 'successDeleteRows', array(count($data), '{rowCount}' => count($data))), null, $sql);

		$this->sendJSON($response);
	}

	public function actionInput()
	{
		
		$attributes = CJSON::decode(Yii::app()->getRequest()->getParam('attributes'), true);
		$column = Yii::app()->getRequest()->getParam('column');
		$oldValue = Yii::app()->getRequest()->getParam('oldValue');
		$rowIndex = Yii::app()->getRequest()->getParam('rowIndex');

		$row = Row::model()->findByAttributes($attributes);
		$column = $this->db->getSchema($this->schema)->getTable($this->table)->getColumn($column);

		$this->render('input', array(
			'column' => $column,
			'row' => $row,
			'attributes' => $attributes,
			'oldValue' => str_replace("\n", "", $oldValue),
			'rowIndex' => $rowIndex,
		));

	}

	public function actionEdit() 
	{
		$attributes = CJSON::decode(Yii::app()->getRequest()->getParam('attributes'), true);
		
		$row = Row::model()->findByAttributes($attributes);

		if($newRow = Yii::app()->getRequest()->getParam('Row')) 
		{
			$response = new AjaxResponse();
			
			foreach($newRow AS $name=>$value)
			{

				// SET
				if(is_array($value))
				{
					$value = implode("," , $value);
				} 
				
				// FILE
				elseif(isset($_FILES['Row']['name'][$name]) && strlen($_FILES['Row']['name'][$name]) > 0)
				{
					$value = file_get_contents($_FILES['Row']['tmp_name'][$name]);
				}
				else if (strlen($value) == 0)
				{
					continue;
				}
				
				$options = Yii::app()->getRequest()->getParam($name);
				
				if($options['function'])
				{
					$row->setFunction($name, $options['function']);
				}
		
				if(isset($options['null']))
				{
					$value = null;
				}
				
				$row->setAttribute($name, $value);
				
			}
			
			
			try {
				
				$sql = $row->save();
				$response->refresh = true;
				$response->addNotification('success', Yii::t('core', 'successUpdateRow'), null, $sql);
				
			}
			catch(DbException $ex) 
			{
				$response->refresh = true;
				$response->addNotification('error', Yii::t('core', 'updatingRowFailed'), $ex->getText(), $ex->getSql());
			}
			
			$this->sendJSON($response);
			
		}
		
		CHtml::generateRandomIdPrefix();
		
		$data = array(
			'row' => $row,
			'functions' => Row::$functions,
			'attributes' => $attributes,
		);
		
		$data['formBody'] = $this->renderPartial('formBody', $data, true);
		
		$this->render('edit', $data);
		
		
	}
	
	public function actionDownload()
	{
		$key = CJSON::decode(Yii::app()->getRequest()->getParam('key'), true);
		$column = Yii::app()->getRequest()->getParam('column');

		$content = Row::model()->findByAttributes($key)->getAttribute($column);
		
		$filename = $column;
		
		// Try finding out mime type of string (fileinfo extensions is installed)
		if(class_exists('finfo', false))
		{
			$finfo = new finfo(FILEINFO_MIME);
			$mimeType = $finfo->buffer($content);
			
			header('Content-Type: ' . $mimeType);
			
			// Try finding correct extension
			preg_match('/\/([a-zA-Z_\-0-9]+)/i', $mimeType, $extension);
			
			if(isset($extension[1]))
			{
				$ext = $extension[1];
				if($ext == "x-gzip")
				{
					$ext = "tar.gz";
				}
				elseif($ext == "x-tar")
				{
					$ext = "tar";
				}
				
				$filename .= "." . $ext;
			}
			
		}
		

blog.liiion911.ru/chive/protected/views/row/edit.php
<script type="text/javascript">
	$(document).ready(function() {
		$('#attributes_<?php echo CHtml::$idPrefix; ?>').val('<?php echo CJSON::encode($attributes); ?>');
	});
</script>

<?php echo CHtml::form('', 'post', array('id' => CHtml::$idPrefix)); ?>
	<input type="hidden" name="attributes" value="" id="attributes_<?php echo CHtml::$idPrefix; ?>" />
	<input type="hidden" name="schema" value="<?php echo $this->schema; ?>" />
	<input type="hidden" name="table" value="<?php echo $this->table; ?>" />
	<h1>
		<?php echo Yii::t('core', ($row->isNewRecord ? 'insertRow' : 'editRow')); ?>
	</h1>
	<?php echo $formBody; ?>
	<?php echo Html::submitFormArea(); ?>
<?php echo CHtml::endForm(); ?>

blog.liiion911.ru/chive/protected/views/row/formBody.php
<table class="list">
	<colgroup>
		<col style="width: 100px;" />
		<col class="type" />
		<col style="width: 100px;" />
		<col class="checkbox" />
		<col />
	</colgroup>
	<thead>
	<tr>
		<th><?php echo Yii::t('core', 'field'); ?></th>
		<th><?php echo Yii::t('core', 'type'); ?></th>
		<th><?php echo Yii::t('core', 'function'); ?></th>
		<th><?php echo Yii::t('core', 'null'); ?></th>
		<th><?php echo Yii::t('core', 'value'); ?></th>
	</tr>
	</thead>
	<tbody>
	<?php $i = 10; ?>
	<?php foreach($row->getMetaData()->tableSchema->columns AS $column)
	{ ?>
	<tr>
		<?php $columnName = CHtml::encode($column->name); ?>
		<td style="font-weight: bold;"><?php echo $columnName; ?></td>
		<td><?php echo strlen($column->dbType) > 50 ? substr($column->dbType, 0, 50) . "..." : $column->dbType ?></td>
		<td>
			<?php if(!in_array(DataType::getBaseType($column->dbType), array('set', 'enum')))
		{ ?>
			<?php echo CHtml::dropDownList($columnName . '[function]', '', $functions); ?>
			<?php } ?>
		</td>
		<td class="center">
			<?php echo ($column->allowNull
				? CHtml::checkBox($columnName . '[null]', is_null($row->getAttribute($columnName))) : ''); ?>
		</td>
		<td>
			<?php $this->widget('InputField', array(
	   'row' => $row, 'column' => $column, 'htmlOptions' => array(
		'onchange' => '$(this).val() ? $("#' . CHtml::$idPrefix . $columnName . '_null").attr("checked", "").change() : void(0);',
		'onkeyup' => '$(this).val() ? $("#' . CHtml::$idPrefix . $columnName . '_null").attr("checked", "").change() : void(0);',
		'tabIndex' => $i,
	)
  )); ?>
		</td>
	</tr>
		<?php $i++; ?>
		<?php } ?>
	</tbody>
</table>

<script type="text/javascript">
	$('table.list tbody input:first').focus();
</script>

blog.liiion911.ru/chive/protected/views/row/input.php
<?php $id = StringUtil::getRandom(10); ?>

<?php echo CHtml::form(Yii::app()->createUrl('row/update'), 'POST', array('id' => 'form_' . $id)); ?>

<div style="padding: 2px 10px;">

	<?php echo CHtml::hiddenField('schema', $this->schema); ?>
	<?php echo CHtml::hiddenField('table', $this->table); ?>
	<?php echo CHtml::hiddenField('column', $column->name); ?>
	<?php echo CHtml::hiddenField('attributes', CJSON::encode($attributes)); ?>
	<?php echo CHtml::hiddenField('isNull', 0, array('id' => 'isNull')); ?>

	<?php $this->widget('InputField', array('row' => $row, 'column'=>$column, 'htmlOptions' => array(
		'id' => 'input_' . $id,
		'autocomplete' => 'off',
		'name' => 'value',
	))); ?>

	<script type="text/javascript">

		$('#form_<?php echo $id; ?>').ajaxForm({
			success:	function(response) {

							editing = false;

							if(response.data.error) {
								reset();
								AjaxResponse.handle(response);
								return false;
							}

							
							$('#input_<?php echo $id; ?>').parent().parent().parent().html(response.data.visibleValue);
							keyData[rowIndex] = response.data.identifier;
							AjaxResponse.handle(response);

						}
		});

		function reset() {
			$('#form_<?php echo $id; ?>').parent().html(<?php echo CJSON::encode($oldValue); ?>);
			editing = false;
		}

		$('#input_<?php echo $id; ?>').select().focus();
		editing = '<?php echo $id; ?>';

	</script>

	<div class="buttonContainer" style="white-space: nowrap">
		<a href="javascript:void(0);" onclick="$('#form_<?php echo $id; ?>').submit();" class="icon button primary">
			<?php echo Html::icon('save', 16, false, 'core.save'); ?>
			<span><?php echo Yii::t('core', 'save'); ?></span>
		</a>
		<a href="javascript:void(0);" onclick="reset();" class="icon button">
			<?php echo Html::icon('delete', 16, false, 'core.cancel'); ?>
			<span><?php echo Yii::t('core', 'cancel'); ?></span>
		</a>
		<?php if($column->allowNull) { ?>
			<?php echo Yii::t('core', 'or'); ?>
			<a href="javascript:void(0);" onclick="$('#isNull').val(1); $('#form_<?php echo $id; ?>').submit();" class="icon button">
				<?php echo Html::icon('null', 16, false, 'core.null'); ?>
				<span><?php echo Yii::t('core', 'setNull'); ?></span>
			</a>
		<?php } ?>
	</div>

</div>

<?php echo CHtml::endForm(); ?>

blog.liiion911.ru/chive/protected/views/row/insert.php
<div class="form">
<?php echo CHtml::form(Yii::app()->createUrl('schema/' . $this->schema . '/tables/' . $this->table . '/insert')); ?>

<?php echo $formBody; ?>

<div class="buttons">
	<input type="hidden" name="insertAndReturn" value="0" id="insertAndReturn" />
	<a href="javascript:void(0);" onclick="$('form').submit();" class="icon button primary">
		<?php echo Html::icon('add', 16, false, 'core.insert'); ?>
		<span><?php echo Yii::t('core', 'insert'); ?></span>
	</a>
	<a href="javascript:void(0);" onclick="$('#insertAndReturn').attr('value', 1); $('form').submit();" class="icon button">
		<?php echo Html::icon('arrow_turn_090', 16, false, 'core.insertAndReturnToThisPage'); ?>
		<span><?php echo Yii::t('core', 'insertAndReturnToThisPage'); ?></span>
	</a>
</div>

<script type="text/javascript">
	$('form').ajaxForm({
		success: function(response) {
			AjaxResponse.handle(response);
		}
	});
</script>

<input type="submit" name="submitButton" style="display: none;" />

<?php echo CHtml::endForm(); ?>