blog.liiion911.ru/chive/protected/controllers/RowController.php
<?php

/*
 * Chive - web based MySQL database management
 * Copyright (C) 2010 Fusonic GmbH
 *
 * This file is part of Chive.
 *
 * Chive is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Chive is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */


class RowController extends Controller
{
	public $schema;
	public $table;
	public $view;
	
	/**
	 * @var Table
	 */
	public $_table;

	/**
	 * @var Default layout for this controller
	 */
	public $layout = 'schema';

	public function __construct($id, $module=null)
	{
		if(Yii::app()->request->isAjaxRequest)
			$this->layout = false;
			
		$request = Yii::app()->getRequest();
		
		$this->schema =	$request->getParam('schema');
		$this->table = $request->getParam('table');
		
		$this->_table = Table::model()->findByPk(array(
			'TABLE_SCHEMA' => $this->schema,
			'TABLE_NAME' => $this->table,
		));
		
		if($this->_table->TABLE_TYPE == 'VIEW')
		{
			$this->view = $this->table;
		}
		
		parent::__construct($id, $module);
		$this->connectDb($this->schema);
		
		// Set row values
		Row::$db = $this->db;
		Row::$schema = $this->schema;
		Row::$table = $this->table;
		
	}

	/**
	 * Insert a new row
	 * 
	 */
	public function actionInsert()
	{
		$response = new AjaxResponse();
		
		if($this->view)
		{
			$this->layout = '_view';
		}
		else
		{
			$this->layout = '_table';
		}

		$row = new Row();
		
		if(isset($_POST['Row']))
		{
			
			foreach($_POST['Row'] AS $attribute=>$value) 
			{
				// NULL value
				if(isset($_POST[$attribute]['null']))
				{
					$row->setAttribute($attribute, null);
				}
	
				// RAW
				// @todo (rponudic) implement multiple sets
				elseif('type' == 'multiple_set')
				{
					
				}
				
				// FILE
				elseif(isset($_FILES['Row']['tmp_name'][$attribute]) && is_file($_FILES['Row']['tmp_name'][$attribute]))
				{
					
					$file = '0x' . bin2hex(file_get_contents($_FILES['Row']['tmp_name'][$attribute]));
					$row->setHex($attribute);
					$row->setAttribute($attribute, $file);
					
				}
				
				// DEFAULT
				else
				{
					$row->setAttribute($attribute, $value);
				}
				
				// FUNCTIONS
				if(isset($_POST[$attribute]['function']) && $_POST[$attribute]['function'])
				{
					$row->setFunction($attribute, $_POST[$attribute]['function']);
				}
				
			}
			
			try 
			{
				$sql = $row->insert();
				
				// Try to find last inserted id if this table has an auto increment value
				if($this->_table->getHasAutoIncrementColumn())
				{
					$notification = Yii::t('core', 'successInsertRowWithIdX', array(
						"{id}" => $this->db->getLastInsertID(),
					));	
				}
				else
				{
					$notification = Yii::t('core', 'successInsertRow');
				}
				
				$response->addNotification('success', $notification, null, $sql);
				
				if($_POST['insertAndReturn'])
				{
					$response->refresh = true;
				}
				else
				{
					$response->redirectUrl = '#tables/' . $this->table . '/browse';
				}
				
			}
			catch (DbException $ex) 
			{
				$response->refresh = false;
				$response->addNotification('error', Yii::t('core', 'errorInsertRow'), $ex->getText(), $ex->getSql());
			}
			
			$this->sendJSON($response);
		
		}
		elseif(isset($_POST['attributes']))
		{
			$attributes = CJSON::decode($_POST['attributes'], true);
			$fromRow = Row::model()->findByAttributes($attributes);
			
			foreach($this->_table->columns as $column)
			{
				if($column->EXTRA != "auto_increment")
				{
					$row->{$column->COLUMN_NAME} = $fromRow->{$column->COLUMN_NAME};
				}
			}
		}
		
		$data = array(
			'row' => $row,
			'functions' => Row::$functions,
		);
		
		$data['formBody'] = $this->renderPartial('formBody', $data, true);
		
		$this->render('insert', $data);

	}
	
	public function actionUpdate()
	{

		$response = new AjaxResponse();

		// Take other solution::
		$newValue = Yii::app()->getRequest()->getParam('value');
		$column = Yii::app()->getRequest()->getParam('column');
		$isNull = Yii::app()->getRequest()->getParam('isNull');
		$attributes = CJSON::decode(Yii::app()->getRequest()->getParam('attributes'), true);
		
		$rows = Row::model()->findAllByAttributes($attributes);
		$row = $rows[0];
		
		// FILE (blob)
		if(isset($_FILES['value']))
		{
			$row->setHex($column);
			$newValue = '0x' . bin2hex(file_get_contents($_FILES['value']['tmp_name']));
			// Refresh if type s file 
			$response->refresh = true;
		}

		if($isNull)
		{
			$newValue = null;
		}
		
		try {

			$row->setAttribute($column, $newValue);
			$sql = $row->save();
			
			$showFullColumnContent = Yii::app()->user->settings->get('showFullColumnContent', 'schema.table.browse', $this->schema . '.' . $this->table);
			
			$visibleValue = CHtml::encode($row->getAttribute($column));
			
			if($isNull)
			{
				$visibleValue = '<span class="null">NULL</span>';
			}
			elseif(!$showFullColumnContent)
			{
				$visibleValue = StringUtil::cutText($visibleValue, 100);
			}

			$response->addData(null, array(
				'value' => ($isNull ? 'NULL' : $row->getAttribute($column)),
				'column' => $column,
				'identifier' => $row->getIdentifier(),
				'isNull' => $isNull,
				'visibleValue' => $visibleValue
			));
			
			$cmd = new CDbCommand($this->db, 'SHOW WARNINGS');
			$warnings = $cmd->queryAll(true);
			
			if(count($warnings) > 0)
			{
				$response->refresh = true;
				foreach($warnings AS $warning)
				{
					$response->addNotification('warning', $warning['Message'], null);
				}
			}
			
			$response->addNotification('success', Yii::t('core', 'successUpdateRow'), null, $sql);


		}
		catch (DbException $ex)
		{
			$response->addNotification('error', Yii::t('core', 'errorUpdateRow'), $ex->getText(), $ex->getSql());
			$response->addData(null, array('error'=>true));
		}

		$this->sendJSON($response);

	}

	public function actionDelete()
	{

		$response = new AjaxResponse();

		$data = CJSON::decode($_POST['data'], true);
		
		$sql = "";
		
		try
		{
			foreach($data AS $attributes)
			{
				$row = Row::model()->findByAttributes($attributes);
				$sql .= $row->delete() . "\n\n";
				
			}
		}
		catch (DbException $ex)
		{
			$response->addNotification('error', Yii::t('core', 'errorDeleteRow'), $ex->getText(), $sql, array('isSticky'=>true));
		}

		$response->refresh = true;
		$response->addNotification('success', Yii::t('core', 'successDeleteRows', array(count($data), '{rowCount}' => count($data))), null, $sql);

		$this->sendJSON($response);
	}

	public function actionInput()
	{
		
		$attributes = CJSON::decode(Yii::app()->getRequest()->getParam('attributes'), true);
		$column = Yii::app()->getRequest()->getParam('column');
		$oldValue = Yii::app()->getRequest()->getParam('oldValue');
		$rowIndex = Yii::app()->getRequest()->getParam('rowIndex');

		$row = Row::model()->findByAttributes($attributes);
		$column = $this->db->getSchema($this->schema)->getTable($this->table)->getColumn($column);

		$this->render('input', array(
			'column' => $column,
			'row' => $row,
			'attributes' => $attributes,
			'oldValue' => str_replace("\n", "", $oldValue),
			'rowIndex' => $rowIndex,
		));

	}

	public function actionEdit() 
	{
		$attributes = CJSON::decode(Yii::app()->getRequest()->getParam('attributes'), true);
		
		$row = Row::model()->findByAttributes($attributes);

		if($newRow = Yii::app()->getRequest()->getParam('Row')) 
		{
			$response = new AjaxResponse();
			
			foreach($newRow AS $name=>$value)
			{

				// SET
				if(is_array($value))
				{
					$value = implode("," , $value);
				} 
				
				// FILE
				elseif(isset($_FILES['Row']['name'][$name]) && strlen($_FILES['Row']['name'][$name]) > 0)
				{
					$value = file_get_contents($_FILES['Row']['tmp_name'][$name]);
				}
				else if (strlen($value) == 0)
				{
					continue;
				}
				
				$options = Yii::app()->getRequest()->getParam($name);
				
				if($options['function'])
				{
					$row->setFunction($name, $options['function']);
				}
		
				if(isset($options['null']))
				{
					$value = null;
				}
				
				$row->setAttribute($name, $value);
				
			}
			
			
			try {
				
				$sql = $row->save();
				$response->refresh = true;
				$response->addNotification('success', Yii::t('core', 'successUpdateRow'), null, $sql);
				
			}
			catch(DbException $ex) 
			{
				$response->refresh = true;
				$response->addNotification('error', Yii::t('core', 'updatingRowFailed'), $ex->getText(), $ex->getSql());
			}
			
			$this->sendJSON($response);
			
		}
		
		CHtml::generateRandomIdPrefix();
		
		$data = array(
			'row' => $row,
			'functions' => Row::$functions,
			'attributes' => $attributes,
		);
		
		$data['formBody'] = $this->renderPartial('formBody', $data, true);
		
		$this->render('edit', $data);
		
		
	}
	
	public function actionDownload()
	{
		$key = CJSON::decode(Yii::app()->getRequest()->getParam('key'), true);
		$column = Yii::app()->getRequest()->getParam('column');

		$content = Row::model()->findByAttributes($key)->getAttribute($column);
		
		$filename = $column;
		
		// Try finding out mime type of string (fileinfo extensions is installed)
		if(class_exists('finfo', false))
		{
			$finfo = new finfo(FILEINFO_MIME);
			$mimeType = $finfo->buffer($content);
			
			header('Content-Type: ' . $mimeType);
			
			// Try finding correct extension
			preg_match('/\/([a-zA-Z_\-0-9]+)/i', $mimeType, $extension);
			
			if(isset($extension[1]))
			{
				$ext = $extension[1];
				if($ext == "x-gzip")
				{
					$ext = "tar.gz";
				}
				elseif($ext == "x-tar")
				{
					$ext = "tar";
				}
				
				$filename .= "." . $ext;
			}
			
		}
		

blog.liiion911.ru/chive/protected/views/global/browse.php
<div id="deleteRowDialog" title="<?php echo Yii::t('core', 'deleteRows'); ?>" style="display: none">
	<?php echo Yii::t('core', 'doYouReallyWantToDeleteSelectedRows'); ?>
</div>

<?php if($model->showInput) { ?>

	<?php echo CHtml::form(Yii::app()->createUrl($model->formTarget), 'post', array('id' => 'queryForm')); ?>
	<table style="width: 100%;" id="browseTable">
		<tr>
			<td id="browseTable_ColLeft">
				<?php $this->widget('AceEditor', array(
					    'id' => 'query',
					   	'htmlOptions' => array('name' => 'query'),
						'value' => $model->getOriginalQueries(),
						'autogrow' => true,
					)); ?>
				<div class="buttons">
					<a href="javascript:void(0);" onclick="$('#queryForm').submit();" class="icon button primary">
						<?php echo Html::icon('execute', 16, false, 'core.execute'); ?>
						<span><?php echo Yii::t('core', 'execute'); ?></span>
					</a>
					<a class="icon button" href="javascript:void(0);" onclick="Bookmark.add('<?php echo $model->schema; ?>', (editAreaLoader ? editAreaLoader.getValue('query') : $('#query').val()));">
						<?php echo Html::icon('bookmark_add'); ?>
						<span><?php echo Yii::t('core', 'bookmark'); ?></span>
					</a>
				</div>
			</td>
			<td style="vertical-align: top; padding: 2px 5px; width: 300px" id="browseTable_ColRight">
				<a class="icon button" href="javascript:void(0);" onclick="Profiling.toggle();">
					<?php if( Yii::app()->user->settings->get('profiling')) {?>
						<?php echo Html::icon('square_green', 16, false, null, array('id' => 'profiling_indicator')); ?>
					<?php } else { ?>
						<?php echo Html::icon('square_red', 16, false, null, array('id' => 'profiling_indicator')); ?>
					<?php } ?>
					<span><?php echo Yii::t('core', 'profiling'); ?></span>
				</a>
				<br/><br/>
				<a class="icon button" href="javascript:void(0);" onclick="$.post(baseUrl + '/ajaxSettings/toggle', {
						name: 'showFullColumnContent',
						scope: 'schema.table.browse',
						object: '<?php echo $model->schema; ?>.<?php echo $model->table; ?>'
					}, function() {
						chive.refresh();
					});">
					<?php if( Yii::app()->user->settings->get('showFullColumnContent', 'schema.table.browse', $model->schema . '.' .  $model->table)) {?>
						<?php echo Html::icon('square_green'); ?>
					<?php } else { ?>
						<?php echo Html::icon('square_red'); ?>
					<?php } ?>
					<span><?php echo Yii::t('core', 'showFullColumnContent'); ?></span>
				</a>
			</td>
		</tr>
	</table>

	<?php echo CHtml::endForm(); ?>

<?php } ?>

<?php if($model->hasResultSet() && $model->getData()) { ?>

	<div class="list">
		<div class="buttonContainer">
			<?php 
				if($model->getQueryType() != "explain" && $model->getPagination() != null)
				{
					$this->widget('LinkPager',array('pages'=>$model->getPagination()));
				} 
			?>
		</div>

		<?php $i = 0; ?>
		<table class="list <?php if($model->getIsUpdatable()) { ?>addCheckboxes editable<?php } ?>" style="width: auto; min-width: 200px;" id="browse">
			<colgroup>
				<col class="checkbox" />
				<?php if(isset($type) && $type == 'select' && $model->singleTableSelect) { ?>
					<col class="action" />
					<col class="action" />
					<col class="action" />
				<?php } ?>
				<?php foreach ($model->getColumns() AS $column) { ?>
					<?php echo '<col />'; ?>
				<?php } ?>
			</colgroup>
			<thead>
				<tr>
					<?php if($model->getQueryType() == 'select' && $model->singleTableSelect) { ?>
						<th><input type="checkbox" /></th>
						<th></th>
						<th></th>
						<th></th>
					<?php } ?>
					<?php foreach ($model->getColumns ()AS $column) { ?>
						<th>
							<?php echo ($model->getQueryType() == 'select' ? $model->getSort()->link(CHtml::encode($column)) : CHtml::encode($column)); ?>
						</th>
					<?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach($model->getData() AS $row) { ?>
					<tr>
						<?php if($model->getQueryType() == 'select' && $model->singleTableSelect) { ?>
							<td>
								<input type="checkbox" name="browse[]" value="row_<?php echo $i; ?>" />
							</td>
							<td class="action">
								<a href="javascript:void(0);" class="icon" onclick="globalBrowse.deleteRow(<?php echo $i; ?>);">
									<?php echo Html::icon('delete', 16, false, 'core.delete'); ?>
								</a>
							</td>
							<td class="action">
								<a href="javascript:void(0);" class="icon" onclick="globalBrowse.editRow(<?php echo $i; ?>);">
									<?php echo Html::icon('edit', 16, false, 'core.edit'); ?>
								</a>
							</td>
							<td class="action">
								<a href="javascript:void(0);" class="icon" onclick="globalBrowse.insertAsNewRow(<?php echo $i; ?>, '<?php echo $model->table; ?>')">
									<?php echo Html::icon('insert', 16, false, 'core.insert'); ?>
								</a>
							</td>
						<?php } ?>
						
						<?php  if($model->getQueryType() == "explain") { ?> 
						
							<?php foreach($row AS $key => $value)	{ ?>
								<td class="<?php echo $key; ?>">
									<span><?php echo is_null($value) ? '<span class="null">NULL</span>' : (Yii::app()->user->settings->get('showFullColumnContent', 'schema.table.browse', $model->schema . '.' .  $model->table) ? htmlspecialchars($value) : StringUtil::cutText(htmlspecialchars($value), 100)); ?></span>
								</td>
							<?php } ?>
						
						<?php } else { ?>
							<?php foreach($row AS $key=>$value) { ?>
								<td class="<?php echo $key; ?>">
									<?php if($model->singleTableSelect && DataType::getInputType($model->getTable()->columns[$key]->dbType) == "file" && $value) { ?>
										<?php if($model->hasPrimaryKey()) { ?>
										<a href="javascript:void(0);" class="icon" onclick="globalBrowse.download('<?php echo Yii::app()->createUrl('row/download'); ?>', {key: JSON.stringify(keyData[<?php echo $i; ?>]), column: '<?php echo $key; ?>', table: '<?php echo $model->table; ?>', schema: '<?php echo $model->schema; ?>'})">
											<?php echo Html::icon('save'); ?> 
											<?php echo Formatter::fileSize(strlen($value)); ?>
										</a>
										<?php } else { ?>
											<?php echo Formatter::fileSize(strlen($value)); ?>
										<?php }?>
									<?php } elseif($model->table !== null) { ?>
										<span><?php echo is_null($value) ? '<span class="null">NULL</span>' : (Yii::app()->user->settings->get('showFullColumnContent', 'schema.table.browse', $model->schema . '.' .  $model->table) ? htmlspecialchars($value) : StringUtil::cutText(htmlspecialchars($value), 100)); ?></span>
									<?php } else { ?>
										<span><?php echo is_null($value) ? '<span class="null">NULL</span>' : (Yii::app()->user->settings->get('showFullColumnContent', 'schema.browse', $model->schema) ? htmlspecialchars($value) : StringUtil::cutText(htmlspecialchars($value), 100)); ?></span>
									<?php } ?>
								</td>
							<?php } ?>
						<?php } ?>
					</tr>
					<?php $i++; ?>
				<?php } ?>
			</tbody>
			<?php if($model->getQueryType() != "explain" && $model->getPagination() != null) { ?>
			<tfoot>
				<tr>
					<th colspan="<?php echo 4 + count($row); ?>">
						<?php echo Yii::t('core', 'showingRowsOfRows', array('{start}' => $model->getStart(), '{end}' => min($model->getStart() + $model->getPagination()->getPagesize(), $model->getTotal()), '{total}' => $model->getTotal())); ?>
					</th>
				</tr>
			</tfoot>
			<?php } ?>
		</table>

	<div class="buttonContainer">
		<?php if ($model->getQueryType() == 'select' && $model->singleTableSelect) { ?>
			<div class="withSelected left">
				<span class="icon">
					<?php echo Html::icon('arrow_turn_090'); ?>
					<span><?php echo Yii::t('core', 'withSelected'); ?></span>
				</span>
				<a class="icon button" href="javascript:void(0)" onclick="globalBrowse.deleteRows()">
					<?php echo Html::icon('delete', 16, false, 'core.delete'); ?>
					<span><?php echo Yii::t('core', 'delete'); ?></span>
				</a>
				<a class="icon button" href="javascript:void(0)" onclick="globalBrowse.exportRows()">
					<?php echo Html::icon('save', 16, false, 'core.export'); ?>
					<span><?php echo Yii::t('core', 'export'); ?></span>
				</a>
			</div>
			<?php $keyData = $model->getKeyData(); 
				  if (count($keyData) > 0) 
				  { ?>
				<script type="text/javascript">
					var keyData = <?php echo CJSON::encode($keyData); ?>;
				</script>
			<?php } ?>
		<?php } ?>
	</div>
	<div class="buttonContainer">
		<?php if($model->getQueryType() != "explain" && $model->getPagination() != null) { ?>
		<?php $this->widget('LinkPager',array('pages'=>$model->getPagination())); ?>
		<?php } ?>
	</div>

<?php } elseif($model->execute) { ?>
	<?php echo Yii::t('core', 'emptyResultSet'); ?>
<?php } ?>


<script type="text/javascript">
	globalBrowse.setup();
	AjaxResponse.handle(<?php echo $model->getResponse(); ?>);
	globalPost = { query: <?php echo CJSON::encode($model->getOriginalQueries()); ?> };
</script>

blog.liiion911.ru/chive/protected/views/global/export.php
<?php if($model->view == 'form') { ?>

	<?php echo CHtml::form('', 'post', array('id' => 'Export')); ?>
		<?php if($model->selectedObjects) { ?>
		<div style="float: left; width: 250px">
			<?php if($model->objects) { ?>
				<?php echo CHtml::dropDownList('Export[objects][]', $model->selectedObjects, $model->objects, array('size' => 20, 'multiple' => true, 'style' => 'width: 100%')); ?>
			<?php } ?>
		</div>
		<?php } ?>
		<div style="<?php if($model->selectedObjects) { echo "margin-left: 260px;"; } ?> width: 600px">
			<?php $firstExporter = current(array_keys($model->exporters)); ?>
			<div id="exporterType">
				<fieldset>
					<legend><?php echo Yii::t('core', 'type'); ?></legend>
					<?php echo CHtml::radioButtonList('Export[exporter]', $firstExporter, $model->exporters, array('separator' => ' &nbsp; ')); ?>
				</fieldset>
			</div>
			<div id="exporterSettings">
				<?php foreach($model->exporterInstances AS $exporter) { ?>
					<div id="exporterSettings_<?php echo get_class($exporter); ?>">
						<?php echo $exporter->getSettingsView(); ?>
					</div>
				<?php } ?>
			</div>
			<div>
				<a href="javascript:void(0)" onclick="globalExport.view()" class="icon button primary">
					<?php echo Html::icon('search', 16, false, 'export.show'); ?>
					<span><?php echo Yii::t('core', 'show'); ?></span>
				</a>
				<a href="javascript:void(0)" onclick="globalExport.save()" class="icon button">
					<?php echo Html::icon('save', 16, false, 'export.download'); ?>
					<span><?php echo Yii::t('core', 'download'); ?></span>
				</a>
				<?php if(function_exists('gzencode')) { ?>
					<a href="javascript:void(0)" onclick="globalExport.save('gzip')" class="icon button">
						<?php echo Html::icon('save', 16, false, 'export.download'); ?>
						<span>Gzip</span>
					</a>
				<?php } ?>
				<?php if(function_exists('bzcompress')) { ?>
					<a href="javascript:void(0)" onclick="globalExport.save('bzip2')" class="icon button">
						<?php echo Html::icon('save', 16, false, 'export.download'); ?>
						<span>Bzip2</span>
					</a>
				<?php } ?>

				<?php echo CHtml::hiddenField('Export[action]', ''); ?>
				<?php echo CHtml::hiddenField('Export[compression]', ''); ?>
				<?php echo CHtml::hiddenField('Export[rows]', CJSON::encode($model->getRows())); ?>
			</div>
		</div>
	<?php echo CHtml::endForm(); ?>

	<script type="text/javascript">
	setTimeout(function() {
		globalExport.setup();
		<?php if(@ini_get('xdebug.profiler_enable')) { ?>
			Notification.add('warning', lang.get('core', 'warning'), lang.get('core', 'xDebugExportWarning'));
		<?php } ?>
	}, 500);
	</script>

<?php } else { ?>

	<?php
	// If we use the Yii textarea htmlspecialchars is called with the charset parameter > htmlspecialchars returns an empty string.
	echo CHtml::tag('textarea', array('style' => 'height: 500px', 'wrap' => 'off'), htmlspecialchars($model->result, ENT_QUOTES));
	?>

<?php } ?>

blog.liiion911.ru/chive/protected/views/global/import.php
<?php if($model->view == 'form') { ?>

	<?php echo CHtml::form($model->formTarget, 'post', array('id' => 'Import')); ?>
		<?php echo CHtml::hiddenField("MAX_FILE_SIZE", ConfigUtil::getMaxUploadSize() - 1000); ?>
		<?php echo CHtml::hiddenField("Import", "true"); ?>
		<fieldset>
			<legend><?php echo Yii::t('core', 'importFile'); ?></legend>
			<?php echo CHtml::fileField('file', '', array()); ?>&nbsp;
			(<?php echo Yii::t('core', 'maximum'); ?>: <?php echo ConfigUtil::getMaxUploadSize(true); ?>)
			<br />
			<br />
			<?php //echo Yii::t('core', 'characterSet', array(1)); ?><br />
			<?php //echo CHtml::activeDropDownList($model, 'fromCharacterSet', CHtml::listData($model->characterSets, 'name', 'name')); ?>
			<b><?php echo Yii::t('core', 'notice'); ?></b><br />
			<?php echo Yii::t('core', 'compressionWillBeAutomaticallyDetected'); ?>
		</fieldset>
		<fieldset>
			<legend><?php echo Yii::t('core', 'settings'); ?></legend>
			<?php echo CHtml::activeCheckBox($model, 'partialImport'); ?>
			<?php echo CHtml::activeLabel($model, 'partialImport');?>
		</fieldset>
		<div class="buttons">
			<a href="javascript:void(0);" onclick="$('#Import').submit();" class="icon button primary"> 
				<?php echo Html::icon('import'); ?>
				<span><?php echo Yii::t('core', 'import'); ?></span> 
			</a> 
		</div>
	<?php echo CHtml::endForm(); ?>
	
	<script type="text/javascript">
		setTimeout(function() {
			globalImport.setup();
		}, 500);
	</script>
	
	<?php if($model->fileUploadError) { ?>
		<script type="text/javascript">
		Notification.add('error', lang.get('core', 'errorUploadingFile'));
		</script>
	<?php } ?>

<?php } elseif($model->view == 'submit') { ?>

	<div id="progressbar" style="height: 20px;"></div><br/>
	
	<table class="list" id="messages" style="display: none;">
		<colgroup>
			<col style="width: 20px;">
			<col>
			<col style="width: 20px;">
		</colgroup>
		<thead>
			<tr>
				<th colspan="3"><?php echo Yii::t('core', 'information'); ?></th>
			</tr>
		</thead>
		<tbody id="messagesContent">
		</tbody>
	</table>
	
	<br/>
	
	<div id="buttonContainer" class="buttons" style="display: none">
		<a href="javascript:void(0);" onclick="AjaxResponse.handle(lastResponse);" class="icon button primary">
			<?php echo Html::icon('success', 16, false, 'core.ok'); ?>
			<span><?php echo Yii::t('core', 'ok'); ?></span>
		</a>
	</div>
	
	<script type="text/javascript">

			var errorCount = 0;
			var lastResponse = "";

			$("#progressbar").progressbar({
				value: 1
			});
	
			function doRequest(_position, _executedQueries)
			{
				$.getJSON("<?php echo $model->formTarget; ?>", {
					position: 				_position, 
					file:					'<?php echo $model->file; ?>',
					fileSize:				'<?php echo $model->fileSize; ?>',
					totalExecutedQueries:	_executedQueries
				},
				function(response)
				{

					lastResponse = response;

					if(response.data.error)
					{
						if(!errorCount)
						{
							$('#messages').show();
						}
						
						$.each(response.notifications, function() {

							html = '<tr class="' + (errorCount % 2 == 0 ? 'even' : 'odd') + '">' + 
										'<td>' + 
											'<span class="icon">' +
												'<img class="icon" src="' + iconPath + '/16/' + this.type + '.png" />' +
												
											'</span>' + 
										'</td>' + 
										'<td>' + 
											'<span>' + this.title + '</span>' + 
										'</td>' +
										'<td>' +
											'<img class="icon" src="' + iconPath + '/16/accordion.png" style="cursor: pointer;" onclick="$(this).parent().parent().next().toggle();"/>' +
										'</td>' +
									'</tr>' +
									'<tr style="display: none;"><td colspan="3"><pre class="sql">' + this.code  + '</pre></td></tr>';

							$('#messagesContent').append(html);				
							errorCount++;
							
						});
						
					}
					else if(response.data.finished)
					{
						$('#progressbar').progressbar('value', 100);
						chive.loadingIndicator = true;
						
						if(errorCount == 0)
						{
							AjaxResponse.handle(response);	
						}
						else
						{
							$('#buttonContainer').show();
						}
						
						return false;
					}
	
					doRequest(response.data.position, response.data.totalExecutedQueries);
					$('#progressbar').progressbar('value', response.data.position / <?php echo $model->fileSize; ?> * 100);
					 
				});
			}

			doRequest(0, 0);
	
	</script>


<?php } ?>